version: '3.8'

services:
  movies_db:
    container_name: movies_db
    image: "postgres:13"
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - movies_data:/var/lib/postgresql/data

volumes: 
  movies_data: {}
